# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit JNAB230203.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)


## ----SESingGrad---------------------------------------------------------------
reala <- -3; realb <- 5; realc <- 0.5; realr <- 0.7; realm <- 1 # underlying parameters
x <- 1:11 # x values; 11 data points
y <- reala + realb * realr^(x - realm) + realc * x # linear + exponential function
testdat <- data.frame(x, y) # save in a data frame
strt <- list(a = -3, b = 5, c = 0.5, r = 0.7, m = 1) # give programs a good start
jform <- y ~ a + b * r^(x - m) + c * x # Formula
library(nlsr)
linexp2 <- try(nlxb(jform, data = testdat, start = strt, trace = FALSE))
linexp2 # Note singular values of Jacobian in rightmost column
# We get an error with nls()
linexp <- try(nls(jform, data = testdat, start = strt, trace = FALSE))


## ----nlswtx, echo=TRUE--------------------------------------------------------
weed <- c(5.308, 7.24, 9.638, 12.866, 17.069, 23.192, 31.443,
          38.558, 50.156, 62.948, 75.995, 91.972)
tt <- 1:12
weeddf <- data.frame(tt, weed)
wts <- 0.5^tt # simple weights
frmlogis <- weed ~ Asym/(1 + exp((xmid - tt)/scal))
Asym<-1; xmid<-1; scal<-1
nowt<-nls(weed ~ SSlogis(tt, Asym, xmid, scal)) # UNWEIGHTED
nowt
nowt$m$resid() # This has UNWEIGHTED residual and Jacobian. Does NOT take coefficients.
usewt <- nls(weed ~ SSlogis(tt, Asym, xmid, scal), weights=wts)
usewt
usewt$m$resid() # WEIGHTED. Does NOT take coefficients.
source("nlsModel.R")
nmod0 <- nlsModel(frmlogis, data=weeddf, start=c(Asym=1, xmid=1, scal=1), wts=wts)
nmod0$resid() # Parameters are supplied in nlsModel() `start` above.
nmod <- nlsModel(frmlogis, data=weeddf, start=coef(usewt), wts=wts)
nmod$resid()


## ----tetrarun-----------------------------------------------------------------
time <- c( 1,  2,  3,  4,  6 , 8, 10, 12, 16)
conc <- c( 0.7, 1.2, 1.4, 1.4, 1.1, 0.8, 0.6, 0.5, 0.3)
NLSdata <- data.frame(time,conc)
NLSstart <- c(lrc1 = -2, lrc2 = 0.25, A1 = 150, A2 = 50) # a starting vector (named!)
NLSformula <- conc ~ A1 * exp(-exp(lrc1) * time) + A2 * exp(-exp(lrc2) * time)
tryit <- try(nls(NLSformula, data = NLSdata, start = NLSstart, trace = TRUE))
print(tryit)


## ----log4ways, echo=TRUE, eval=FALSE------------------------------------------
#> DNase1 <- subset(DNase, Run == 1) # select the data
#> ## using a selfStart model - do not specify the starting parameters
#> fm1 <- nls(density ~ SSlogis(log(conc), Asym, xmid, scal), DNase1)
#> summary(fm1)
#> 
#> ## using conditional linearity - leave out the Asym parameter
#> fm2 <- nls(density ~ 1 / (1 + exp((xmid - log(conc)) / scal)),
#>                  data = DNase1, start = list(xmid = 0, scal = 1),
#>                  algorithm = "plinear")
#> summary(fm2)
#> 
#> ## without conditional linearity
#> fm3 <- nls(density ~ Asym / (1 + exp((xmid - log(conc)) / scal)),
#>                  data = DNase1,
#>                  start = list(Asym = 3, xmid = 0, scal = 1))
#> summary(fm3)
#> 
#> ## using Port's nl2sol algorithm
#> fm4 <- try(nls(density ~ Asym / (1 + exp((xmid - log(conc)) / scal)),
#>                  data = DNase1, start = list(Asym = 3, xmid = 0, scal = 1),
#>                  algorithm = "port"))
#> summary(fm4)
#> 
#> ## using conditional linearity AND Asym does NOT work
#> fm2a <- try(nls(density ~ Asym / (1 + exp((xmid - log(conc)) / scal)),
#>                  data = DNase1, start = list(Asym=3, xmid = 0, scal = 1),
#>                  algorithm = "plinear", trace = TRUE))
#> summary(fm2a)


## ----nlsindx1-----------------------------------------------------------------
## The muscle dataset in MASS is from an experiment on muscle
## contraction on 21 animals.  The observed variables are Strip
## (identifier of muscle), Conc (Cacl concentration) and Length
## (resulting length of muscle section).
if(! requireNamespace("MASS", quietly = TRUE)) stop("Need MASS pkg")
mm<- MASS::muscle[1:12,] # take only 1st few values of Strip (TRUNCATION OF EXAMPLE)
mm<-droplevels(mm) # remove unused levels after truncation
nlev <- nlevels(mm)
withAutoprint({
  ## The non linear model considered is
  ##       Length = alpha + beta*exp(-Conc/theta) + error
  ## where theta is constant. For now alpha and beta do NOT vary with Strip.
  with(mm, table(Strip)) # 2, 3 or 4 obs per strip
  nl <- nlevels(mm$Strip)
  ## We first use the plinear algorithm to fit an overall model,
  ## ignoring that alpha and beta might vary with Strip.
  musc.1 <- nls(Length ~ cbind(1, exp(-Conc/th)), mm,
                start = list(th = 1), algorithm = "plinear")
  summary(musc.1)

  ## Then we use nls' indexing feature for parameters in non-linear
  ## models to use the conventional algorithm to fit a model in which
  ## alpha and beta vary with Strip.  The starting values are provided
  ## by the previously fitted model.
  ## Note that with indexed parameters, the starting values must be
  ## given in a list (with names):
  b <- coef(musc.1)
  musc.2 <- nls(Length ~ a[Strip] + b[Strip]*exp(-Conc/th), data=mm,
                start = list(a = rep(b[2], nl), b = rep(b[3], nl), th = b[1]))
  summary(musc.2)
})


## ----chkbound-----------------------------------------------------------------
# bhobbsX.R ## bounded formula specification of problem using Hobbs Weed problem
weed <- c(5.308, 7.24, 9.638, 12.866, 17.069, 23.192, 31.443,
          38.558, 50.156, 62.948, 75.995, 91.972)
tt <- 1:12
wf <- data.frame(y = weed, tt = tt)
st <- c(b1 = 1, b2 = 1, b3 = 1) # a default starting vector (named!)
wmods <- y ~ 100 * b1 / (1 + 10 * b2 * exp(-0.1 * b3 * tt)) ## Scaled model
require(minpack.lm)
# Hobbs scaled problem with bounds, formula specification
anlxb1 <- nlxb(wmods, start = st, data = wf, lower = c(0, 0, 0), upper = c(2, 6, 3))
cat("Using nlsr::nlxb():")
print(anlxb1)
## nlsLM seems NOT to work properly with bounds
anlsLM1b <- nlsLM(wmods, start = st, data = wf, lower = c(0, 0, 0), upper = c(2, 6, 3))
cat("\n"); cat("using minpack.lm::nlsLM():")
print(anlsLM1b)
anlsb<-nls(wmods, start = st, data = wf, algorithm = "port", 
           lower = c(0, 0, 0), upper = c(2, 6, 3))
cat("Using nls with 'port':")
print(anlsb)

